### ISSUE TITLE
Background refresh

### ISSUE THREAD

**Issue by jm991** [JohanDegraeve/xdripswift#142]
Hi,

I'm sorry if this is the wrong place to ask this, but is xDripSwift enabled for background app refresh on iOS? I didn't see it under `Settings > General > Background App Refresh` and was wondering if I'm missing readings when the screen is locked.

**Comment by JohanDegraeve** [comment]
The app should work in the background, however iOS may and does close the app at unpredictable times.

The "background app refresh" is not used here and will not help.
To shortly explain how background app refresh works, there's two methods.
- as a developer you can request that the app is allowed to do background upgrades. If requested, the goal is that iOS will bring the app from suspended to active, allowing the app to verify eg if there's news content available.
The problem here is that it is unpredictable when iOS will bring the app from suspended to active.
I've been testing with this some time ago. If for example you would open the app every day at 8:00 in the morning, then you have some chance that iOS will active the app somewhere before 8:00 every day. So it can fetch your news even before you're asking for it.

A totally useful feature.

- or as a developer you can work with remote, silent notifications. A notification is sent by a server, it can be silent, means invisible for the user, but (if background app refresh is enabled) it reactivates the app, and it allows the app to fetch content from a server (or do to posts, which would be applicable for NightScout uploads).
This works, however it would mean we need to send a remote/silent notification every 5 minutes.
Could be useful for xdrip4iOs in follower mode. Then we would need to have a server that sends a silent notification, giving the opportunit to xdrip4iOS to fetch new readings from NS. (would even be much better from battery point of view compared to the mechanism used now in follower mode)

But for xdrip4iOS in master mode, totally useless.
The app does get suspended (not killed), a few seconds after going to the background. But it's the transmitter that is either trying to connect and/or trying to send data that triggers the re-activation of the app.

Unfortunately, as said earlier, iOS may still decide to kill the app, probably based on battery consumption. I experienced that disabling NightScout completely does reduce the chance for the app getting killed.

Missed readings may have other causes, like bugs in xDrip4iOS
