### ISSUE TITLE
Watch agenda option leads to higher battery consumption with FSL2Direct

### ISSUE THREAD

**Issue by liroyvh** [JohanDegraeve/xdripswift#198]
When the Libre2 is directly connected, xdrip4ios updates the Watch-agenda every minute. This leads to the Watch having an increased battery consumption as it is constantly being prevented from going to a deeper sleep and has to wake-up more often than needed. 

Problem report has been submitted by email with debug info.

(updated description and removed, issues 190 and 191 are not related)

**Comment by JohanDegraeve** [comment]
In WatchManager the variable timeStampLastProcessedReading was not set. This variable is needed to check if a new event needs to be created in the calendar or not. Two readings must be at least 4.75 minutes away from each other

Note that this is not the case if there's been a disconnect/reconnect. For instance if you lose connection, then come back in range, you connect, the next reading will be sent to the watch. I don't not change this behaviour because it allows MM and bubble users to force a new reading by disabling/enabling bluetooth

(note also that the implementation is not different for MM, Bubble, Libre 2 - you just noticed this issue because Libre 2 creates a new reading every 1 minute, the others normally only every 5 minutes)
