### ISSUE TITLE
App terminated at night - possible to use "State Preservation and Restoration" from core bluetooth?

### ISSUE THREAD

**Issue by bobhavlin** [JohanDegraeve/xdripswift#201]
Great work on the app!  Thank you!!

I am using v. 4.5.23 and was amazed at how stable it is compared to the app termination issues with Spike, however, last night I had my first OS termination and was wondering if there was anything that could be done to prevent this.  

I see that turning off NS upload might help, but was hoping there was a better solution.  

I found that some apps can run without termination issues and was curious how that was accomplished.  I found the following in [Apples documentation for Core Bluetooth](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html) which suggests that the system detects the bt and relaunches the app to handle the connection.

In the code I see `bluetooth-central` but none of the "State Preservation and Restoration" parts that allegedly allows the system to relaunch the app in the background.  

Have you considered this yet?

**Comment by JohanDegraeve** [comment]
Hi,

this is exactly how it works : 
https://github.com/JohanDegraeve/xdripswift/blob/master/xdrip/BluetoothTransmitter/Generic/BluetoothTransmitter.swift#L363

not only connect launches the app, also disconnect and update value (update value is a situation where there's a connection, but there hasn't been data sent for a longer period so the app is suspended, and then the transmitter sends data, the app will wake up)
https://github.com/JohanDegraeve/xdripswift/blob/master/xdrip/BluetoothTransmitter/Generic/BluetoothTransmitter.swift#L501

https://github.com/JohanDegraeve/xdripswift/blob/master/xdrip/BluetoothTransmitter/Generic/BluetoothTransmitter.swift#L409

Every app works like this (tomato, diabox, xdrip4ios), also Spike does. But in case of Spike this restoration doesn't work, most probably due to the actionscript framework which sits between iOS and the Spike code

as far as your problem concerns , this is the only answer that I can give : https://github.com/JohanDegraeve/xdripswift/wiki/xDrip4iOS-suddenly-stops-giving-readings

**Comment by bobhavlin** [comment]
Thanks for the information!  

In my case it looks like iOS decided "app removed from memory" / "kill the app" which based on my reading of Core Bluetooth and [this QA ](https://developer.apple.com/library/archive/qa/qa1962/_index.html) should have been relaunched in the background when there was a bt connection from transmitter.  I did not see the required `CBCentralManagerOptionRestoreIdentifierKey` in the code, so I was not sure if the system background relaunch would be expected to occur.  

Sorry if I am missing it, but I did not see the required parts for implementation (from [here](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html)):
> Adding Support for State Preservation and Restoration
>State preservation and restoration in Core Bluetooth is an opt-in feature and requires help from your app to work. You can add support for this feature in your app by following this process:
>(Required) Opt in to state preservation and restoration when you allocate and initialize a central or peripheral manager object. This step is described in Opt In to State Preservation and Restoration.
>(Required) Reinstantiate any central or peripheral manager objects after your app is relaunched by the system. This step is described in Reinstantiate Your Central and Peripheral Managers.
>(Required) Implement the appropriate restoration delegate method. This step is described in Implement the Appropriate Restoration Delegate Method.
>(Optional) Update your central and peripheral managers’ initialization process. This step is described in Update Your Initialization Process.

**Comment by JohanDegraeve** [comment]
you're right, it's the first time I see that it's possible to relaunch an app even if it's been removed from memory by iOS or crashed.
I'm not using CBCentralManagerOptionRestoreIdentifierKey, see https://github.com/JohanDegraeve/xdripswift/blob/master/xdrip/BluetoothTransmitter/Generic/BluetoothTransmitter.swift#L524

I'll do the necessary adaptations and if at least everything still works as is, then I'll release this, see if there's less complaints then
