### ISSUE TITLE
Show app badge with decimal

### ISSUE THREAD

**Issue by Jon-b-m** [JohanDegraeve/xdripswift#215]
I have noticed that sometimes the app badge shows blood glucose with 2 digits **with** a decimal, but most of the times it doesn't. If this is something that you can control that would be a nice enhancement, to always have the decimal showing. But perhaps it's just some peculiarity/bug in iOS?   

![image](https://user-images.githubusercontent.com/53905247/113027412-51dec380-918a-11eb-9ff5-78c854f62c1d.png)

**Comment by JohanDegraeve** [comment]
this is a difficult one.
there are two ways to set the badge counter

1. together with a notification
Means the app creates a notification with the value in it. (because you have 'Show BG in Notifications?' switched on)
In that case, the badge value will be set together with the notification.
see https://github.com/JohanDegraeve/xdripswift/blob/54f8da3a00f5b5fbba1aec8be706d24eb4513aeb/xdrip/View%20Controllers/Root%20View%20Controller/RootViewController.swift#L1261

2. not together with a notification.
This is because either 'Show BG in Notifications?'  is not on, or the notification is suppressed for other reasons like there's an alert (if there's an alert notification then there's no normal bg notification), or because it was less than 5 minutes ago that the previous notification was created. Which will happen frequently for Libre 2 users (I assume you're a Libre 2 User ?)
In this case there's another method used to set the badge counter https://github.com/JohanDegraeve/xdripswift/blob/54f8da3a00f5b5fbba1aec8be706d24eb4513aeb/xdrip/View%20Controllers/Root%20View%20Controller/RootViewController.swift#L1305

There's a major difference between those two methods of setting the badge counter
1. when doing it with a notification, it's possible to specify floating point numbers.
2. if it's not done with a notification, it must be an integer, means rounded value

I don't know the best way to solve

It will happen more for Libre 2 users, and also for others as of next release, because it will be possible to specify a minimum interval between two notifications.

A possible solution is not to update the badge counter if the notification is suppressed, but you probably will not like that

**Comment by Jon-b-m** [comment]
Wow, thanks, what a thorough answer! Perhaps it will not be necessary then, because if the the minimum interval is set to 1 for notifications, you will likely get a decimal value more often than not.

**Comment by JohanDegraeve** [comment]
> Wow, thanks, what a thorough answer! Perhaps it will not be necessary then, because if the minimum interval is set to 1 for notifications, you will likely get a decimal value more often than not.

that is correct.
