### ISSUE TITLE
Direct Connect Libre2 Canada

### ISSUE THREAD

**Issue by wiegerthefarmer** [JohanDegraeve/xdripswift#282]
I got my hands on some Canadian Libre2s. I've gotten it directly connected but it's throwing an error when at CGMLibre2Transmitter line 294 (parseBLEData).  I've disabled bluetooth for the Libre2 app and as far as I can tell have done everything I need to. I know that it's been documented that the Canadian Libre2's direct connect isn't working yet...

Just wondering about the state of Canadian decryption. Is there something fundamental that's preventing this from working? Happy to help debug/test to get this working.
![IMG_4533](https://user-images.githubusercontent.com/222517/141767062-d701a3ec-bca8-4001-9dfd-f26af5caebb2.jpg)

**Comment by gui-dos** [comment]
AFAIK, you cannot “login” to a Libre 2 Sense/US/CA/AU if you don’t establish a “Gen2” session first.

If you write to the BLELogin characteristic the single byte `0x20` the sensor replies with 14 bytes which the vendor call a “security challenge”.

This is the first step of a multi-stage protocol that I summed up in <https://github.com/gui-dos/DiaBLE/blob/master/DiaBLE/Gen2.swift>

The @bubbledevteam is trying to allow calling online the native methods on their server that xDrip4iOS5 however is not supporting anymore. On Android they are succeeding because they embedding the Data Processing native library but on iOS this a really hairy challenge…

**Comment by wiegerthefarmer** [comment]
Thanks @gui-dos ! I also have DiaBLE and looking at the data that way. Some great work you're doing!
