### ISSUE TITLE
Libre2 EU sensor Age & Start Date is incorrect.

### ISSUE THREAD

**Issue by aluvare** [JohanDegraeve/xdripswift#316]
The sensor was started the 4th of January:
![image](https://user-images.githubusercontent.com/16783660/149641049-e19c49d8-ba96-46dc-ab59-252adacf0899.jpeg)

And in xDRip:
![image](https://user-images.githubusercontent.com/16783660/149641044-ab078824-2ab8-417f-a932-57e671d3df47.jpeg)

**Comment by JohanDegraeve** [comment]
can you send a problem report? it's in the settings

**Comment by aluvare** [comment]
Sent!

Thx @JohanDegraeve!!

**Comment by JohanDegraeve** [comment]
I should have known : the logs do not show the sensor start, it was too long ago.
can you explain the stems you usually take when you start a new sensor?

**Comment by JohanDegraeve** [comment]
if you're using the transmitter algorithm, what you could try is delete and add again , scan, .. etc

If it still doesn't solve the countdown, then send a new issue report
If you're calibrating the values (ie use xdrip algorithm), then maybe better not to do this because you would need to calibrate again. Then it's better to wait till next sensor

**Comment by aluvare** [comment]
I've doing the process and still happening. Sent by Mail the info!

Thx @JohanDegraeve
