### ISSUE TITLE
Apple Watch irregular icon

### ISSUE THREAD

**Issue by clvsjr9** [JohanDegraeve/xdripswift#319]
Trying to use a new definition for Apple Watch (Serie 3 - 42mm) modular icons but xdrip4iO5 has a problem here:

![fig0](https://user-images.githubusercontent.com/12844781/151198890-0cb688da-4071-42b2-8b83-02aee799e99a.jpg)

![fig2](https://user-images.githubusercontent.com/12844781/151198976-3146c5e5-d7cb-4219-9290-73aba3f62227.PNG)

The Watch app is running 100%. Just the icon for Apple Watch is not ok.

**Comment by paulplant** [comment]
This is a limitation of the older-style modular watchfaces. I can't remember exactly but they are limited to the colour depth (bits) that they can display. As the xDrip4iOS icon has a gradient background, then it cannot display and and the icon shows a white square.

We can look at changing the icons bit-depth so that it displays correctly when using these old-style watchfaces.

A better idea would be to use the newer modular watchfaces (if supported by your WatchOS version).

I'll close this issue and just keep a note of it. The Watch app will receive updates in the next month or so and I'll look into fixing this at the same time.
