### ISSUE TITLE
When Entering Treatments in PM, it creates a duplicate at the AM time

### ISSUE THREAD

**Issue by OliNix** [JohanDegraeve/xdripswift#347]
If I add a treatment in the PM, it adds a duplicate but at the corresponding AM time.

See screenshots attached:
![IMG_0024](https://user-images.githubusercontent.com/16334811/166462206-d1c95f81-8e71-4b2e-8cd3-11615034c41e.PNG)
![IMG_0025](https://user-images.githubusercontent.com/16334811/166462214-9b201117-a48d-40a9-84ac-5b924b37817e.PNG)
![IMG_0026](https://user-images.githubusercontent.com/16334811/166462372-aabb0325-09b4-4ec4-9325-79c5c9ddde45.PNG)
.

**Comment by OliNix** [comment]
Update: Only occurs when entering treatments from 1:00pm-1:59pm

**Comment by paulplant** [comment]
Bug confirmed.

But this seems to be just the way that we are accessing local treatments when in 12hr clock. The Nightscout synced treatment is showing correctly.

So it doesn't duplicate the treatment, it is just showing incorrectly the one you enter, and then downloading it again from NS and displaying it correctly... at least this is what it seems to be doing after a quick look.

**Comment by paulplant** [comment]
More testing done. To me this happens only to treatments that are stored from 2:00pm - 2:59pm (possible due to the hour's time difference to you @OliNix ).

The PM treatments *in this timeframe* are converted to AM treatments when the iPhone is changed from 24hrs to 12hrs clock mode. It is not just a display issue as once changed back to 24hrs mode, the treatments stay in the AM. They can be edited back to the correct time in the PM, but as soon as the 12hr clock mode is selected again, they are immediately changed back to AM treatments.

**Comment by OliNix** [comment]
AM duplicate treatments can be deleted whilst PM versions remain

**Comment by OliNix** [comment]
Issue resolved in 4.10.2
