### ISSUE TITLE
App lose connection with iOS 15.5

### ISSUE THREAD

**Issue by tsaraliev** [JohanDegraeve/xdripswift#367]
Few days ago we changed from Iphone 8 to Iphone 13 mini. The version of iOS is 15.5. It connects with the sensor, it works about 20 minutes, but then lose connection and I am struggling conect it again. All permissions fro battery, background and data are allowed. The sensor is Libre 2 /Europe/. The LibleLink doesnt have permission for Bluethooth. I tried with my husband's Iphone SE 2019, also with iOS 15.5 - it is the same story - works 20 minutes and then lose connection. 
*I dont knwo which version of iOS is the Iphone 8, but It is older, the automatic updates were not allowed.

**Comment by tsaraliev** [comment]
I guess, because the phone is switched off. In few hours, when I get home from work, I will delete xDrip4iOS from the old phone to be surethere is no chance to be working.
On the Iphone 13 mini:
- Screen time control is OFF
- Allowed all permissions for location, batery usage and mobile data.
- LibreLink bluethooth is disabled
- There is no "check" in Background App Refresh, but TestFlight is checked

**Comment by paulplant** [comment]
@tsaraliev  - can this issue be closed?

Or are you still confirming the problem? Thanks!

**Comment by tsaraliev** [comment]
It still loses connection, but I have no more ideas what to do. Sometime it takes few scans to connect, but sometimes its harder. Close the case, we will wait for update.

**Comment by paulplant** [comment]
> It still loses connection, but I have no more ideas what to do. Sometime it takes few scans to connect, but sometimes its harder. Close the case, we will wait for update.

OK... but these are two different issues.

Problems getting a successful NFC scan are one thing, and another thing is that the connection, once established, is lost. But they are two different issues.

The NFC is a common problem for all users unfortunately.

The connection loss is usually user-related (sensor/iPhone etc). It is usually caused by xDrip4iOS getting offloaded from memory by iOS but you seen to infer that you have done all of the usual adjustments to prevent this.

If you leave it connected with the screen lock mode enabled, does this preven it losing connection?
