### ISSUE TITLE
Nightscout and libre 2 upload frequency

### ISSUE THREAD

**Issue by KevinDenys** [JohanDegraeve/xdripswift#371]
Not a real issue but more of a question. What is the frequency of an upload to the nightscout server? The libre 2 gets a new value every 60seconds +-, does it upload it every 60 seconds or does it wait a certain time to do this?

**Comment by JohanDegraeve** [comment]
It will upload only every 5 minutes.
An exception is if there's been a disconnection (between xdrip and cgm), then you will see a new reading being uploaded even if it's less than 5 minutes ago since previous meeting. I did that a sometime for backward compatibility when going from Libre 1 to 2

I also noticed an error recently, sometimes there's two readings uploaded with a time difference of just a few seconds but with different values, happens if you have the smoothing on - but I've not been able yet to fix that

**Comment by KevinDenys** [comment]
And what if there hasnt been an active internet connection for example and outage of 8h. Will it fill in those 8 hours or will it just skip those 8 hours?

**Comment by JohanDegraeve** [comment]
max 7 days and max 300 readings 👍 https://github.com/JohanDegraeve/xdripswift/blob/master/xdrip/Constants/ConstantsNightScout.swift#L8

**Comment by KevinDenys** [comment]
Thank you Johan for the information
