### ISSUE TITLE
Fastlane needs updating from 2.215.0 to 2.219.0

### ISSUE THREAD

**Issue by OliNix** [JohanDegraeve/xdripswift#521]
#######################################################################
# fastlane 2.219.0 is available. You are on 2.215.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################

**Comment by paulplant** [comment]
@dnzxy , is this something we need to look into for the fastlane build?

**Comment by dnzxy** [comment]
This issue is over a month old and by now there’s actually fastlane 2.220.0, but see we should look at this. It solves browser build issues I had recently mentioned that are being tested for Loop.  We should update both that token fix and the fastlane update (LoopWorkspace PRs [125](https://github.com/LoopKit/LoopWorkspace/pull/125) and [126](https://github.com/LoopKit/LoopWorkspace/pull/126)).

**Comment by dnzxy** [comment]
@paulplant this issue can be closed 😊
