### ISSUE TITLE
Data not updating on the complication for Apple Watch?

### ISSUE THREAD

**Issue by podupuis** [JohanDegraeve/xdripswift#529]
For some reason, the data for xdrip on the Apple Watch face doesn't update automatically? Why? I need to manually press on it to get new data. Any fix or suggestions to make it do it automatically?

**Comment by paulplant** [comment]
Complications are not designed for real-time data. This is due to complication restrictions from WatchOS.

There is currently no background refresh in xDrip4iOS 5.1.x. The complications will only update when the Watch app is opened. This was detailed in the release notes for 5.1.0.

Background refresh will be implemented for 5.2.0 but this is still not real-time. It will only updated 2-3 times per hour. Never more. 

I will close this shortly as it isn't actually a bug, but a known item that is already described in the release notes and already addressed.

**Comment by paulplant** [comment]
No comment from @podupuis so we'll close this.
