### ISSUE TITLE
Erroneous +0 BG deltas reported

### ISSUE THREAD

**Issue by aug0211** [JohanDegraeve/xdripswift#544]
See PR #545 

xDrip occasionally reports a +0 BG delta when in fact BG delta is not +0. This most often occurs with +1 or -1 deltas (mgdl). Have discussed in the past but could not find an issue for it. I've implemented a very minor code change that resolves this issue for me. I'm opening the issue to accompany the PR.

I've reproduced this issue across 4 iOS devices and 2 WatchOS devices and both master and dev builds over the past ~6 weeks.

We first suspected multiple sources uploading to Nightscout as the cause. This was addressed and the issue did not resolve. This was not the cause.

Here are recent screen shots showing xDrip reporting a delta of +0, when in fact Nightscout reports a -1 (which is accurate because BG went from 87 to 86).

![image](https://github.com/JohanDegraeve/xdripswift/assets/659845/14417c3d-7b83-41de-bb26-caff233a4e9e)![image](https://github.com/JohanDegraeve/xdripswift/assets/659845/59ef7b2c-644b-495a-b22c-af59dfce733d)![image](https://github.com/JohanDegraeve/xdripswift/assets/659845/e78901c0-6cf3-4415-a3eb-278936e0ac2c)

I have implemented a trivial fix for this which I've tested and validated as working as desired across watch complication, watch app, phone widget, phone live activities, phone app. See PR #545.

**Comment by paulplant** [comment]
The PR you opened worked fine for mg/dL deltas and fixed a long-standing issue that seems to have existed since the very early code was ported over from xDrip+ many years ago. Nobody ever really noticed it, but you're right that it existed!

But once I started troubleshooting, it seemed that the overall calculation for mmol/L had never really worked correctly for certain values either. This is because there are distinct "steps" in the displayed "mg/dL converted to mmol/L" values and this meant that we shouldn't have been just converting the resultant mg/dL delta value into mmol/L.

There is a new commit into the 5.4 staging branch that will finally fix this: 07f4656aec7e92149db024fa9db681b3ed1f474d

This works by first converting (throughout the app) the values into mmol/L (if needed) and then performing the delta calculation and string generation.

@aug0211 , feel free to try building the 5.4 Staging Branch if you fancy giving it a test in both mg/dL and mmol/L.

**Comment by aug0211** [comment]
Hey! I haven't had a chance to test but I think I saw the PR merged, is that right? The fix was pretty straight forward, so can probably close it out if so!

**Comment by paulplant** [comment]
No worries. The actual fix was much less straight forward than the actual PR, but I guess was also addressing a separate issue regarding delta calculations in mmol/L. I'll close..
