### ISSUE TITLE
No sound on Missed Readings alarm

### ISSUE THREAD

**Issue by yochem** [JohanDegraeve/xdripswift#568]
## Problem

I have the same alarm type for both very low alarm and missed readings alarm. The sound works on very low, but not on missed readings. This is dangerous during sleeping, as I don't notice I'm missing readings.

## Expected Behaviour

Sound during alarm for missed readings

## Current Behaviour

No sound during alarm for missed readings, even though it works when very low.

## System Info
- Version: 5.3.3
- Build: 4204
- Model: iPhone 11
- iOS: 17.6.1

## Steps to reproduce
1. Alarm Types > +:
  - Enabled: true
  - Name: "urgent"
  - Vibrate: true
  - Sound: "Wake Up Will You"
  - Override Mute: true
  - Allow Snooze Via Notification: false
  - Default Snooze Time (mins): 15
2. Alarms > Missed readings:
  - Apply from: 00:00
  - Alarm Type: urgent
  - Value (mins): 15

<img width="414" alt="image" src="https://github.com/user-attachments/assets/2eb405d0-3faa-4b2f-a9d0-3aad15d8fa1b">
<img width="414" alt="image" src="https://github.com/user-attachments/assets/650875f3-a587-465b-9ba3-5e06ea0d8ab3">

P.S. I also send an email for this bug via the "send issue report" button in  the app, but the auto-reply made me question if it was the right place. I also don't have facebook.

**Comment by JohanDegraeve** [comment]
Actually override mute doesn't work for missed reading alerts.
You'll need to make sure that your phone is not muted and the volume is high enough.

**Comment by yochem** [comment]
Ah okay, good to know. Is there any particular reason for this?

**Comment by JohanDegraeve** [comment]
If a sound needs to be played while override mute is on, then it's the app that needs to play the sound. To allow an app to play a sound it needs to be runnning.
Low or high alarms are generated by a running app: the app goes from suspended to active by the trigger of a bluetooth event (eg cgm sends value triggers the wake up of the app), the app checks the value that it receives from the CGM and if necessary decides to trigger an alarm. 
An alarm is a notification usually with a sound.
It override mute is on, the app plays the sound and triggers the notification, here the notification is one without sound (otherwise there would be two sounds). If override mute is off, the app triggers a notification with sound but does not play a sound itself. 
Mute status doesn't affect the sound played by the app.

For missed readings it's different: a missed reading is a future planned notification (usually with sound). It's replanned every time there's a new reading. 
If there hasn't been any wake up off the app for the period defined by the future planned notification, then the app can not play the sound because it's not active. So it's the notification that nees to play the sound. Mute status  does affect the sound played by the notification

**Comment by yochem** [comment]
Thank you for your great explanation! Understood, I'll just put my phone off mute during the night. Thank you for this great app!
