### ISSUE TITLE
Unstable connection: back forth scanning / connected

### ISSUE THREAD

**Issue by robinwo** [JohanDegraeve/xdripswift#581]
Sensor: FSL (EU)
Pump: Dash
Platform: iOS18
Version: 5.4.0

My sensor connection status is frequently switching between connected and scanning. 

About 10-20x per day I have no readings anymore. Closing the app fully and restarting it makes readings come in again.

I have ‘Bluetooth’ disabled for the Librelinkup app, and are using no other sensor apps. I have Trio installed for the connection with my pump (Dash).

Is this normal behavior? And if not, any way how I might debug why my sensors always keep losing their connection (and to what)?

**Comment by paulplant** [comment]
For general tech support, much better to use the Facebook group if possible: https://www.facebook.com/groups/853994615056838

But if you are only having this issue with this sensor, then it makes sense that the sensor is faulty and should be replaced.

I understand that you're not also using Trio to connect to the FSL2 via LibreTransmitter, correct? The failure mode you're describing usually happens when the sensor is connecting to a different app.

**Comment by paulplant** [comment]
Closing. Please re-open if this Issue is still relevant.
