### ISSUE TITLE
Apple Watch smart stack issue

### ISSUE THREAD

**Issue by Nifury** [JohanDegraeve/xdripswift#583]
Hello, I noticed an issue with live activities and smart stack. 

When enabling or disabling live activity mirroring for xDrip4iOS, it also affects the mirroring of media apps.

I’ve attached a screen recording that demonstrates the problem more clearly.

Platform: iOS 18.0.1, watchOS 11.0.1
Version: 5.4.1

https://github.com/user-attachments/assets/272afac0-6032-428a-883c-b3107a6d581b

**Comment by Nifury** [comment]
The live activity mirroring settings for each app should be independent, meaning that adjusting the settings for one app should not impact the settings of another.

Currently, it seems that the live activity mirroring settings for Media Apps and xDrip4iOS (as well as Shuggah) are overwriting each other. This suggests that xDrip4iOS and Media Apps might be using the same live activity identifier (or something similar), causing WatchOS to save their settings in the same location.

I hope this explanation makes the issue clear.

**Comment by paulplant** [comment]
Now I understand. Interesting... I've tested it and it's true. And other apps don't seem to provoke this.

No idea why, but will look into it!

**Comment by paulplant** [comment]
I was thinking about this and it's actually easier to figure out than I thought.

So not related to any type of identifiers (as there aren't any in that sense for a Live Activity in order to differentiate between apps), but xDrip4iOS would probably be technically classified as an audio app for the Smart Stack (i.e. any app which can reproduce audio). 

xDrip4iOS has the background audio capability used for follower mode keep-alive.

<img width="400" alt="image" src="https://github.com/user-attachments/assets/cead62c1-688e-4836-a763-287ca817e4f9">

As we can't remove this, I guess the issue will just have to be lived with. Please confirm if you agree to close.
