### ISSUE TITLE
no notification with reading when in follower mode

### ISSUE THREAD

**Issue by JohanDegraeve** [JohanDegraeve/xdripswift#59]
reported by user via messenger

**Comment by JohanDegraeve** [comment]
anybody else having this problem ?

**Comment by zshh** [comment]
What notifications are we talking about exactly? I am running mine in follower mode, just need to know specifics on what I should look after

**Comment by JohanDegraeve** [comment]
The notification that gives the reading.
![IMG_2113](https://user-images.githubusercontent.com/13840461/72895639-2195cc80-3d1e-11ea-9444-c7f1c448270b.PNG)

**Comment by zshh** [comment]
Gotcha, ok that one works fine for me.
iphone 11, ios 13.3.1 beta 2

I have it normally disabled as it wakes up the screen every 5 minutes when it updates which annoys me. Maybe that can be fixed with some ios setting, but I am normally android user so not that into IOS/notification tweaks and settings.

**Comment by JohanDegraeve** [comment]
close as no further complaints
