### ISSUE TITLE
Allow the tomato code to work with the new and old versions of mm2 fw.

### ISSUE THREAD

**Issue by JohanDegraeve** [JohanDegraeve/xdripswift#60]
See https://github.com/NightscoutFoundation/xDrip/pull/1043

**Comment by gui-dos** [comment]
I noticed that while the effective data packet length becomes 369 when the 6 bytes patchInfo are appended, its length is still reported to be 363 when you evaluate

```swift
Int(rxBuffer[1]) << 8 + Int(rxBuffer[2])
```

See my implementation in

https://github.com/gui-dos/DiaBLE/blob/7f2de75e734384eabb5a5ab32086a332a7b8e338/DiaBLE/Transmitter.swift#L210-L222

![miaomiao_datalength](https://user-images.githubusercontent.com/7220550/73156004-a301ac00-40dc-11ea-9164-a17b6669d7ef.png)

**Comment by JohanDegraeve** [comment]
Will this also work with Libre 2 ?

**Comment by gui-dos** [comment]
It is only a simpler way to get the info you otherwise must read via NFC with the custom command 0xA107:

See: https://github.com/NightscoutFoundation/xDrip/blob/edf05f9f867704ec7e59c33dac9bc200517d2fdb/app/src/main/java/com/eveningoutpost/dexdrip/NFCReaderX.java#L366-L370

https://github.com/gui-dos/DiaBLE/blob/9e1619536e9df5a9f85788320e4bf17a5f7bfd1f/DiaBLE/NFC.swift#L62

**Comment by JohanDegraeve** [comment]
MM2 support for Libre 2 is being worked on.
see develop branch, tests with Libre 2 are ongoing
